name: Azure Container Registry + Azure Kubernetes Service + Variables + Secrets

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    env:
      DOCKER_CONTAINER_REGISTRY: groffegithubactions.azurecr.io

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login no Azure Container Registry
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        login-server: ${{ env.DOCKER_CONTAINER_REGISTRY }}
      
      
